[colors.bright]
black = "#4c566a"
blue = "#81a1c1"
cyan = "#8fbcbb"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#eceff4"
yellow = "#ebcb8b"

[colors.cursor]
cursor = "#d8dee9"
text = "#2e3440"

[colors.dim]
black = "#373e4d"
blue = "#68809a"
cyan = "#6d96a5"
green = "#809575"
magenta = "#8c738c"
red = "#94545d"
white = "#aeb3bb"
yellow = "#b29e75"

[colors.normal]
black = "#3b4252"
blue = "#81a1c1"
cyan = "#88c0d0"
green = "#a3be8c"
magenta = "#b48ead"
red = "#bf616a"
white = "#e5e9f0"
yellow = "#ebcb8b"

[colors.primary]
background = "#2e3440"
dim_foreground = "#a5abb6"
foreground = "#d8dee9"

[colors.search.matches]
background = "#88c0d0"
foreground = "CellBackground"

[colors.selection]
background = "#4c566a"
text = "CellForeground"

[colors.vi_mode_cursor]
cursor = "#d8dee9"
text = "#2e3440"

[font]
size = 12

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "Menlo"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[[keyboard.bindings]]
chars = ""
key = 10
mods = "Alt"

[[keyboard.bindings]]
chars = "¡"
key = 18
mods = "Alt"

[[keyboard.bindings]]
chars = "“"
key = 19
mods = "Alt"

[[keyboard.bindings]]
chars = "§"
key = 20
mods = "Alt"

[[keyboard.bindings]]
chars = "£"
key = 21
mods = "Alt"

[[keyboard.bindings]]
chars = "∞"
key = 23
mods = "Alt"

[[keyboard.bindings]]
chars = "™"
key = 22
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 26
mods = "Alt"

[[keyboard.bindings]]
chars = "["
key = 28
mods = "Alt"

[[keyboard.bindings]]
chars = "]"
key = 25
mods = "Alt"

[[keyboard.bindings]]
chars = "'"
key = 24
mods = "Alt"

[[keyboard.bindings]]
chars = "@"
key = 42
mods = "Alt"

[[keyboard.bindings]]
chars = "|"
key = 34
mods = "Alt"

[[keyboard.bindings]]
chars = "'"
key = 10
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¯"
key = 18
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "”"
key = 19
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "$"
key = 20
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "¢"
key = 21
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "‰"
key = 23
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = ""
key = 22
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = '\'
key = 26
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "{"
key = 28
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "}"
key = 25
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "^"
key = 30
mods = "Alt|Shift"

[[keyboard.bindings]]
chars = "º"
key = 49
mods = "Alt|Shift"
