# Font configuration (changes require restart)
font:
  size: 12
  # The normal (roman) font face to use.
  normal:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Regular

  # The bold font face
  bold:
    family: FiraCode Nerd Font
    # Style can be specified to pick a specific face.
    style: Bold

  # The italic font face
  italic:
    family: Menlo
    # Style can be specified to pick a specific face.
    style: Italic

TERM: xterm-256color

# Normal colors
colors:
  primary:
    background: '#2e3440'
    foreground: '#d8dee9'
    dim_foreground: '#a5abb6'
  cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  vi_mode_cursor:
    text: '#2e3440'
    cursor: '#d8dee9'
  selection:
    text: CellForeground
    background: '#4c566a'
  search:
    matches:
      foreground: CellBackground
      background: '#88c0d0'
    footer_bar:
      background: '#434c5e'
      foreground: '#d8dee9'
  normal:
    black: '#3b4252'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#88c0d0'
    white: '#e5e9f0'
  bright:
    black: '#4c566a'
    red: '#bf616a'
    green: '#a3be8c'
    yellow: '#ebcb8b'
    blue: '#81a1c1'
    magenta: '#b48ead'
    cyan: '#8fbcbb'
    white: '#eceff4'
  dim:
    black: '#373e4d'
    red: '#94545d'
    green: '#809575'
    yellow: '#b29e75'
    blue: '#68809a'
    magenta: '#8c738c'
    cyan: '#6d96a5'
    white: '#aeb3bb'

key_bindings:
  - { key: 10,  mods: Alt,        chars: ""    } # alt+dollar
  - { key: 18,  mods: Alt,        chars: "\xA1" } # alt+1
  - { key: 19,  mods: Alt,        chars: "“"    } # alt+2
  - { key: 20,  mods: Alt,        chars: "\xA7" } # alt+3
  - { key: 21,  mods: Alt,        chars: "\xA3" } # alt+4
  - { key: 23,  mods: Alt,        chars: "∞"    } # alt+5
  - { key: 22,  mods: Alt,        chars: "™"    } # alt+6
  - { key: 26,  mods: Alt,        chars: "|"    } # alt+7
  - { key: 28,  mods: Alt,        chars: "\x5B" } # alt+8
  - { key: 25,  mods: Alt,        chars: "\x5D" } # alt+9
  - { key: 24,  mods: Alt,        chars: "\x27" } # alt+´
  - { key: 42,  mods: Alt,        chars: "\x40" } # alt+' (gives @)
  - { key: 34,  mods: Alt,        chars: "\x7C" } # alt+i
  
  - { key: 10,  mods: Alt|Shift,  chars: "\x27" } # alt+shift+dollar
  - { key: 18,  mods: Alt|Shift,  chars: "\xAF" } # alt+shift+1
  - { key: 19,  mods: Alt|Shift,  chars: "”"    } # alt+shift+2
  - { key: 20,  mods: Alt|Shift,  chars: "\x24" } # alt+shift+3
  - { key: 21,  mods: Alt|Shift,  chars: "\xA2" } # alt+shift+4
  - { key: 23,  mods: Alt|Shift,  chars: "‰"    } # alt+shift+5
  - { key: 22,  mods: Alt|Shift,  chars: "\x98" } # alt+shift+6
  - { key: 26,  mods: Alt|Shift,  chars: "\x5C" } # alt+shift+7
  - { key: 28,  mods: Alt|Shift,  chars: "\x7B" } # alt+shift+8
  - { key: 25,  mods: Alt|Shift,  chars: "\x7D" } # alt+shift+9
  - { key: 30,  mods: Alt|Shift,  chars: "\x5E" } # alt+shift+^
  - { key: 49,  mods: Alt|Shift,  chars: "\xBA" } # alt+shift+'
